<?php

namespace Triv\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForumImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumImageRepository extends EntityRepository
{
}
