<?php

namespace Triv\AnimesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnimesImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimesImageRepository extends EntityRepository
{
}
