<?php

namespace Triv\AnimesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CritiqueAnimesImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CritiqueAnimesImageRepository extends EntityRepository
{
}
