<?php

namespace Triv\CoreBundle\Entity;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
	 public function getNb($ref,$ref_id,$vote) {
 
        return $this->createQueryBuilder('v')
                        ->select('COUNT(v)')
                        ->where('v.ref = :r')
                        ->setParameter('r', $ref)
						->andWhere('v.refId = :rid')
						->setParameter('rid', $ref_id)
						->andWhere('v.vote = :vote')
						->setParameter('vote', $vote)
                        ->getQuery()
 
                        ->getSingleScalarResult();
 
    }
	
	
}
