<?php

namespace Triv\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function getNb() {
 
        return $this->createQueryBuilder('u')
 
                        ->select('COUNT(u)')
 
                        ->getQuery()
 
                        ->getSingleScalarResult();
 
    }
}
