<?php

namespace Triv\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserImageRepository extends EntityRepository
{
}
